const PER_PAGE_CHANGE = 'PER_PAGE_CHANGE'
const CURRENT_PAGE_CHANGE = 'CURRENT_PAGE_CHANGE'

const REQUEST_REPOS = 'REQUEST_REPOS'
const REQUEST_REPOS_SUCCESS = 'REQUEST_REPOS_SUCCESS'
const REQUEST_REPOS_ERROR = 'REQUEST_REPOS_ERROR'
const GET_REPOS = 'GET_REPOS'
const CANCEL_FETCHING_REPOS = 'CANCEL_FETCHING_REPOS'
const CHANGE_CURRENT_REQUEST_KEY = 'CHANGE_CURRENT_REQUEST_KEY'

export {
	PER_PAGE_CHANGE,
	CURRENT_PAGE_CHANGE,
	REQUEST_REPOS,
	REQUEST_REPOS_SUCCESS,
	REQUEST_REPOS_ERROR,
	GET_REPOS,
	CANCEL_FETCHING_REPOS,
	CHANGE_CURRENT_REQUEST_KEY
}